// Code generated by protoc-gen-go. DO NOT EDIT.
// source: receiver.proto

/*
Package comm is a generated protocol buffer package.

It is generated from these files:
	receiver.proto

It has these top-level messages:
	Msg
	BinMsg
	Conf
*/
package comm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg struct {
	Replica   string            `protobuf:"bytes,1,opt,name=replica" json:"replica,omitempty"`
	Vclock    map[string]uint32 `protobuf:"bytes,2,rep,name=vclock" json:"vclock,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Operation string            `protobuf:"bytes,3,opt,name=operation" json:"operation,omitempty"`
	Create    *Msg_CREATE       `protobuf:"bytes,4,opt,name=create" json:"create,omitempty"`
	Delete    *Msg_DELETE       `protobuf:"bytes,5,opt,name=delete" json:"delete,omitempty"`
	Append    *Msg_APPEND       `protobuf:"bytes,6,opt,name=append" json:"append,omitempty"`
	Expunge   *Msg_EXPUNGE      `protobuf:"bytes,7,opt,name=expunge" json:"expunge,omitempty"`
	Store     *Msg_STORE        `protobuf:"bytes,8,opt,name=store" json:"store,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Msg) GetReplica() string {
	if m != nil {
		return m.Replica
	}
	return ""
}

func (m *Msg) GetVclock() map[string]uint32 {
	if m != nil {
		return m.Vclock
	}
	return nil
}

func (m *Msg) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *Msg) GetCreate() *Msg_CREATE {
	if m != nil {
		return m.Create
	}
	return nil
}

func (m *Msg) GetDelete() *Msg_DELETE {
	if m != nil {
		return m.Delete
	}
	return nil
}

func (m *Msg) GetAppend() *Msg_APPEND {
	if m != nil {
		return m.Append
	}
	return nil
}

func (m *Msg) GetExpunge() *Msg_EXPUNGE {
	if m != nil {
		return m.Expunge
	}
	return nil
}

func (m *Msg) GetStore() *Msg_STORE {
	if m != nil {
		return m.Store
	}
	return nil
}

type Msg_Element struct {
	Value    string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Tag      string `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	Contents []byte `protobuf:"bytes,3,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (m *Msg_Element) Reset()                    { *m = Msg_Element{} }
func (m *Msg_Element) String() string            { return proto.CompactTextString(m) }
func (*Msg_Element) ProtoMessage()               {}
func (*Msg_Element) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Msg_Element) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Msg_Element) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Msg_Element) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Msg_CREATE struct {
	User       string       `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Mailbox    string       `protobuf:"bytes,2,opt,name=mailbox" json:"mailbox,omitempty"`
	AddMailbox *Msg_Element `protobuf:"bytes,3,opt,name=addMailbox" json:"addMailbox,omitempty"`
}

func (m *Msg_CREATE) Reset()                    { *m = Msg_CREATE{} }
func (m *Msg_CREATE) String() string            { return proto.CompactTextString(m) }
func (*Msg_CREATE) ProtoMessage()               {}
func (*Msg_CREATE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Msg_CREATE) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Msg_CREATE) GetMailbox() string {
	if m != nil {
		return m.Mailbox
	}
	return ""
}

func (m *Msg_CREATE) GetAddMailbox() *Msg_Element {
	if m != nil {
		return m.AddMailbox
	}
	return nil
}

type Msg_DELETE struct {
	User       string         `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Mailbox    string         `protobuf:"bytes,2,opt,name=mailbox" json:"mailbox,omitempty"`
	RmvMailbox []*Msg_Element `protobuf:"bytes,3,rep,name=rmvMailbox" json:"rmvMailbox,omitempty"`
	RmvMails   []string       `protobuf:"bytes,4,rep,name=rmvMails" json:"rmvMails,omitempty"`
}

func (m *Msg_DELETE) Reset()                    { *m = Msg_DELETE{} }
func (m *Msg_DELETE) String() string            { return proto.CompactTextString(m) }
func (*Msg_DELETE) ProtoMessage()               {}
func (*Msg_DELETE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *Msg_DELETE) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Msg_DELETE) GetMailbox() string {
	if m != nil {
		return m.Mailbox
	}
	return ""
}

func (m *Msg_DELETE) GetRmvMailbox() []*Msg_Element {
	if m != nil {
		return m.RmvMailbox
	}
	return nil
}

func (m *Msg_DELETE) GetRmvMails() []string {
	if m != nil {
		return m.RmvMails
	}
	return nil
}

type Msg_APPEND struct {
	User    string       `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Mailbox string       `protobuf:"bytes,2,opt,name=mailbox" json:"mailbox,omitempty"`
	AddMail *Msg_Element `protobuf:"bytes,3,opt,name=addMail" json:"addMail,omitempty"`
}

func (m *Msg_APPEND) Reset()                    { *m = Msg_APPEND{} }
func (m *Msg_APPEND) String() string            { return proto.CompactTextString(m) }
func (*Msg_APPEND) ProtoMessage()               {}
func (*Msg_APPEND) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *Msg_APPEND) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Msg_APPEND) GetMailbox() string {
	if m != nil {
		return m.Mailbox
	}
	return ""
}

func (m *Msg_APPEND) GetAddMail() *Msg_Element {
	if m != nil {
		return m.AddMail
	}
	return nil
}

type Msg_EXPUNGE struct {
	User    string         `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Mailbox string         `protobuf:"bytes,2,opt,name=mailbox" json:"mailbox,omitempty"`
	RmvMail []*Msg_Element `protobuf:"bytes,3,rep,name=rmvMail" json:"rmvMail,omitempty"`
}

func (m *Msg_EXPUNGE) Reset()                    { *m = Msg_EXPUNGE{} }
func (m *Msg_EXPUNGE) String() string            { return proto.CompactTextString(m) }
func (*Msg_EXPUNGE) ProtoMessage()               {}
func (*Msg_EXPUNGE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 4} }

func (m *Msg_EXPUNGE) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Msg_EXPUNGE) GetMailbox() string {
	if m != nil {
		return m.Mailbox
	}
	return ""
}

func (m *Msg_EXPUNGE) GetRmvMail() []*Msg_Element {
	if m != nil {
		return m.RmvMail
	}
	return nil
}

type Msg_STORE struct {
	User    string         `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Mailbox string         `protobuf:"bytes,2,opt,name=mailbox" json:"mailbox,omitempty"`
	RmvMail []*Msg_Element `protobuf:"bytes,3,rep,name=rmvMail" json:"rmvMail,omitempty"`
	AddMail *Msg_Element   `protobuf:"bytes,4,opt,name=addMail" json:"addMail,omitempty"`
}

func (m *Msg_STORE) Reset()                    { *m = Msg_STORE{} }
func (m *Msg_STORE) String() string            { return proto.CompactTextString(m) }
func (*Msg_STORE) ProtoMessage()               {}
func (*Msg_STORE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 5} }

func (m *Msg_STORE) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Msg_STORE) GetMailbox() string {
	if m != nil {
		return m.Mailbox
	}
	return ""
}

func (m *Msg_STORE) GetRmvMail() []*Msg_Element {
	if m != nil {
		return m.RmvMail
	}
	return nil
}

func (m *Msg_STORE) GetAddMail() *Msg_Element {
	if m != nil {
		return m.AddMail
	}
	return nil
}

type BinMsg struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *BinMsg) Reset()                    { *m = BinMsg{} }
func (m *BinMsg) String() string            { return proto.CompactTextString(m) }
func (*BinMsg) ProtoMessage()               {}
func (*BinMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BinMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Conf struct {
	Status uint32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *Conf) Reset()                    { *m = Conf{} }
func (m *Conf) String() string            { return proto.CompactTextString(m) }
func (*Conf) ProtoMessage()               {}
func (*Conf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Conf) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Msg)(nil), "comm.Msg")
	proto.RegisterType((*Msg_Element)(nil), "comm.Msg.Element")
	proto.RegisterType((*Msg_CREATE)(nil), "comm.Msg.CREATE")
	proto.RegisterType((*Msg_DELETE)(nil), "comm.Msg.DELETE")
	proto.RegisterType((*Msg_APPEND)(nil), "comm.Msg.APPEND")
	proto.RegisterType((*Msg_EXPUNGE)(nil), "comm.Msg.EXPUNGE")
	proto.RegisterType((*Msg_STORE)(nil), "comm.Msg.STORE")
	proto.RegisterType((*BinMsg)(nil), "comm.BinMsg")
	proto.RegisterType((*Conf)(nil), "comm.Conf")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Receiver service

type ReceiverClient interface {
	Incoming(ctx context.Context, in *BinMsg, opts ...grpc.CallOption) (*Conf, error)
}

type receiverClient struct {
	cc *grpc.ClientConn
}

func NewReceiverClient(cc *grpc.ClientConn) ReceiverClient {
	return &receiverClient{cc}
}

func (c *receiverClient) Incoming(ctx context.Context, in *BinMsg, opts ...grpc.CallOption) (*Conf, error) {
	out := new(Conf)
	err := grpc.Invoke(ctx, "/comm.Receiver/Incoming", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Receiver service

type ReceiverServer interface {
	Incoming(context.Context, *BinMsg) (*Conf, error)
}

func RegisterReceiverServer(s *grpc.Server, srv ReceiverServer) {
	s.RegisterService(&_Receiver_serviceDesc, srv)
}

func _Receiver_Incoming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiverServer).Incoming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comm.Receiver/Incoming",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiverServer).Incoming(ctx, req.(*BinMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Receiver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comm.Receiver",
	HandlerType: (*ReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Incoming",
			Handler:    _Receiver_Incoming_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "receiver.proto",
}

func init() { proto.RegisterFile("receiver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x4d, 0x93, 0x26, 0xed, 0x6b, 0x57, 0xd7, 0x41, 0x65, 0x08, 0x8b, 0x94, 0x82, 0x52,
	0x58, 0x2c, 0x58, 0x2f, 0xea, 0x6d, 0xdd, 0x0d, 0x22, 0xd8, 0xb5, 0x8c, 0xab, 0x78, 0xcd, 0x26,
	0xcf, 0x12, 0x36, 0x99, 0x09, 0x93, 0x69, 0xd9, 0xfd, 0x03, 0x3c, 0x7b, 0xf5, 0xcf, 0x95, 0xf9,
	0xd1, 0x4d, 0x59, 0x29, 0xd2, 0xc3, 0xde, 0xe6, 0x3b, 0xef, 0x93, 0xf7, 0x6b, 0x5e, 0x1e, 0x3c,
	0x94, 0x98, 0x61, 0xb1, 0x46, 0x39, 0xad, 0xa5, 0x50, 0x82, 0x04, 0x99, 0xa8, 0xaa, 0xf1, 0x9f,
	0x1e, 0xf8, 0xf3, 0x66, 0x49, 0x28, 0x44, 0x12, 0xeb, 0xb2, 0xc8, 0x52, 0xea, 0x8d, 0xbc, 0x49,
	0x9f, 0x6d, 0x24, 0x79, 0x05, 0xe1, 0x3a, 0x2b, 0x45, 0x76, 0x45, 0x3b, 0x23, 0x7f, 0x32, 0x98,
	0x3d, 0x9d, 0xea, 0x0f, 0xa7, 0xf3, 0x66, 0x39, 0xfd, 0x6e, 0xee, 0x13, 0xae, 0xe4, 0x0d, 0x73,
	0x10, 0x39, 0x82, 0xbe, 0xa8, 0x51, 0xa6, 0xaa, 0x10, 0x9c, 0xfa, 0xc6, 0x55, 0x7b, 0x41, 0x26,
	0x10, 0x66, 0x12, 0x53, 0x85, 0x34, 0x18, 0x79, 0x93, 0xc1, 0xec, 0xb0, 0x75, 0x76, 0xca, 0x92,
	0x93, 0x8b, 0x84, 0x39, 0xbb, 0x26, 0x73, 0x2c, 0x51, 0x21, 0xed, 0xde, 0x25, 0xcf, 0x92, 0xcf,
	0x89, 0x26, 0xad, 0x5d, 0x93, 0x69, 0x5d, 0x23, 0xcf, 0x69, 0x78, 0x97, 0x3c, 0x59, 0x2c, 0x92,
	0xf3, 0x33, 0xe6, 0xec, 0xe4, 0x18, 0x22, 0xbc, 0xae, 0x57, 0x7c, 0x89, 0x34, 0x32, 0xe8, 0xe3,
	0x16, 0x4d, 0x7e, 0x2c, 0xbe, 0x9d, 0x7f, 0x4c, 0xd8, 0x86, 0x20, 0x2f, 0xa0, 0xdb, 0x28, 0x21,
	0x91, 0xf6, 0x0c, 0xfa, 0xa8, 0x45, 0xbf, 0x5e, 0x7c, 0x61, 0x09, 0xb3, 0xd6, 0x78, 0x0e, 0x51,
	0x52, 0x62, 0x85, 0x5c, 0x91, 0x27, 0xd0, 0x5d, 0xa7, 0xe5, 0x0a, 0x5d, 0x07, 0xad, 0x20, 0x87,
	0xe0, 0xab, 0x74, 0x49, 0x3b, 0xe6, 0x4e, 0x1f, 0x49, 0x0c, 0xbd, 0x4c, 0x70, 0x85, 0x5c, 0x35,
	0xa6, 0x43, 0x43, 0x76, 0xab, 0xe3, 0x02, 0x42, 0xdb, 0x08, 0x42, 0x20, 0x58, 0x35, 0x28, 0x9d,
	0x33, 0x73, 0xd6, 0xaf, 0x54, 0xa5, 0x45, 0x79, 0x29, 0xae, 0x9d, 0xbf, 0x8d, 0x24, 0xaf, 0x01,
	0xd2, 0x3c, 0x9f, 0x3b, 0xa3, 0xff, 0x4f, 0x75, 0x36, 0x45, 0xb6, 0x05, 0xc5, 0xbf, 0x3c, 0x08,
	0x6d, 0x2b, 0xf7, 0x8f, 0x25, 0xab, 0x75, 0x1b, 0xcb, 0xdf, 0x11, 0xab, 0x85, 0x74, 0xc9, 0x4e,
	0x35, 0x34, 0x18, 0xf9, 0x93, 0x3e, 0xbb, 0xd5, 0x71, 0x06, 0xa1, 0x7d, 0xa7, 0x3d, 0xd3, 0x38,
	0x86, 0xc8, 0x55, 0xb3, 0xbb, 0xde, 0x0d, 0x11, 0xe7, 0x10, 0xb9, 0x17, 0xde, 0x3f, 0x8a, 0xcb,
	0x74, 0x77, 0xa5, 0x1b, 0x22, 0xfe, 0xed, 0x41, 0xd7, 0x4c, 0xc7, 0x3d, 0x06, 0xd9, 0xae, 0x3b,
	0xf8, 0x6f, 0xdd, 0xef, 0x60, 0xb0, 0xf5, 0x97, 0xea, 0x61, 0xbc, 0xc2, 0x1b, 0x97, 0x95, 0x3e,
	0xb6, 0x43, 0xab, 0x53, 0x3a, 0x70, 0x43, 0xfb, 0xbe, 0xf3, 0xd6, 0x1b, 0x1f, 0x41, 0xf8, 0xa1,
	0xe0, 0x7a, 0x39, 0x10, 0x08, 0xf2, 0x54, 0xd9, 0xcd, 0x30, 0x64, 0xe6, 0x3c, 0x7e, 0x0e, 0xc1,
	0xa9, 0xe0, 0x3f, 0xc9, 0x33, 0x08, 0x1b, 0x95, 0xaa, 0x55, 0x63, 0xac, 0x07, 0xcc, 0xa9, 0xd9,
	0x0c, 0x7a, 0xcc, 0x2d, 0x1c, 0xf2, 0x12, 0x7a, 0x9f, 0x78, 0x26, 0xaa, 0x82, 0x2f, 0xc9, 0xd0,
	0x26, 0x6b, 0x3d, 0xc7, 0x60, 0x95, 0xf6, 0x34, 0x7e, 0x70, 0x19, 0x9a, 0xcd, 0xf4, 0xe6, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0xf1, 0x92, 0x94, 0xab, 0x04, 0x00, 0x00,
}
