workspace:
  base: /go
  path: src/github.com/go-pluto/pluto

pipeline:
  test:
    image: golang:1.8
    commands:
    - make test-pki
    - make test-public
    - make test

  build:
    image: golang:1.8
    commands:
    - make build
    when:
      event: [ push, tag ]

  docker:
    image: plugins/docker
    repo: gopluto/pluto
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push

  docker:
    image: plugins/docker
    repo: gopluto/pluto
    secrets: [ docker_username, docker_password ]
    tag: [ 0.4, 0.4.1 ]
    when:
      event: tag

  github-release:
    image: plugins/github-release
    files: pluto
    when:
      event: tag
