// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

/*
Package imap is a generated protocol buffer package.

It is generated from these files:
	node.proto

It has these top-level messages:
	Context
	Confirmation
	Command
	Reply
	Await
	MailFile
*/
package imap

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Context struct {
	ClientID   string `protobuf:"bytes,1,opt,name=clientID" json:"clientID,omitempty"`
	UserName   string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	RespWorker string `protobuf:"bytes,3,opt,name=respWorker" json:"respWorker,omitempty"`
}

func (m *Context) Reset()                    { *m = Context{} }
func (m *Context) String() string            { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()               {}
func (*Context) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Context) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *Context) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Context) GetRespWorker() string {
	if m != nil {
		return m.RespWorker
	}
	return ""
}

type Confirmation struct {
	Status uint32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *Confirmation) Reset()                    { *m = Confirmation{} }
func (m *Confirmation) String() string            { return proto.CompactTextString(m) }
func (*Confirmation) ProtoMessage()               {}
func (*Confirmation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Confirmation) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type Command struct {
	Text     string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	ClientID string `protobuf:"bytes,2,opt,name=clientID" json:"clientID,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Command) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Command) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type Reply struct {
	Text   string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Status uint32 `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Reply) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Reply) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type Await struct {
	NumBytes uint32 `protobuf:"varint,1,opt,name=numBytes" json:"numBytes,omitempty"`
}

func (m *Await) Reset()                    { *m = Await{} }
func (m *Await) String() string            { return proto.CompactTextString(m) }
func (*Await) ProtoMessage()               {}
func (*Await) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Await) GetNumBytes() uint32 {
	if m != nil {
		return m.NumBytes
	}
	return 0
}

type MailFile struct {
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *MailFile) Reset()                    { *m = MailFile{} }
func (m *MailFile) String() string            { return proto.CompactTextString(m) }
func (*MailFile) ProtoMessage()               {}
func (*MailFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MailFile) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Context)(nil), "imap.Context")
	proto.RegisterType((*Confirmation)(nil), "imap.Confirmation")
	proto.RegisterType((*Command)(nil), "imap.Command")
	proto.RegisterType((*Reply)(nil), "imap.Reply")
	proto.RegisterType((*Await)(nil), "imap.Await")
	proto.RegisterType((*MailFile)(nil), "imap.MailFile")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	Prepare(ctx context.Context, in *Context, opts ...grpc.CallOption) (*Confirmation, error)
	Close(ctx context.Context, in *Context, opts ...grpc.CallOption) (*Confirmation, error)
	Select(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error)
	Create(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error)
	Delete(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error)
	List(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error)
	AppendBegin(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Await, error)
	AppendEnd(ctx context.Context, in *MailFile, opts ...grpc.CallOption) (*Reply, error)
	Expunge(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error)
	Store(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Prepare(ctx context.Context, in *Context, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := grpc.Invoke(ctx, "/imap.Node/Prepare", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Close(ctx context.Context, in *Context, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := grpc.Invoke(ctx, "/imap.Node/Close", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Select(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/imap.Node/Select", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Create(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/imap.Node/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Delete(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/imap.Node/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) List(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/imap.Node/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) AppendBegin(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Await, error) {
	out := new(Await)
	err := grpc.Invoke(ctx, "/imap.Node/AppendBegin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) AppendEnd(ctx context.Context, in *MailFile, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/imap.Node/AppendEnd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Expunge(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/imap.Node/Expunge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Store(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/imap.Node/Store", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	Prepare(context.Context, *Context) (*Confirmation, error)
	Close(context.Context, *Context) (*Confirmation, error)
	Select(context.Context, *Command) (*Reply, error)
	Create(context.Context, *Command) (*Reply, error)
	Delete(context.Context, *Command) (*Reply, error)
	List(context.Context, *Command) (*Reply, error)
	AppendBegin(context.Context, *Command) (*Await, error)
	AppendEnd(context.Context, *MailFile) (*Reply, error)
	Expunge(context.Context, *Command) (*Reply, error)
	Store(context.Context, *Command) (*Reply, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Context)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imap.Node/Prepare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Prepare(ctx, req.(*Context))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Context)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imap.Node/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Close(ctx, req.(*Context))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imap.Node/Select",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Select(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imap.Node/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Create(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imap.Node/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Delete(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imap.Node/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).List(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_AppendBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).AppendBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imap.Node/AppendBegin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).AppendBegin(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_AppendEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).AppendEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imap.Node/AppendEnd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).AppendEnd(ctx, req.(*MailFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Expunge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Expunge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imap.Node/Expunge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Expunge(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imap.Node/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Store(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "imap.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepare",
			Handler:    _Node_Prepare_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Node_Close_Handler,
		},
		{
			MethodName: "Select",
			Handler:    _Node_Select_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Node_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Node_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Node_List_Handler,
		},
		{
			MethodName: "AppendBegin",
			Handler:    _Node_AppendBegin_Handler,
		},
		{
			MethodName: "AppendEnd",
			Handler:    _Node_AppendEnd_Handler,
		},
		{
			MethodName: "Expunge",
			Handler:    _Node_Expunge_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _Node_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}

func init() { proto.RegisterFile("node.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0x86, 0xf9, 0x69, 0x29, 0x1c, 0xe0, 0x5b, 0xcc, 0xe2, 0x4b, 0xc3, 0xc2, 0x98, 0x8a, 0x68,
	0xd4, 0x74, 0x21, 0x2b, 0x97, 0x50, 0x30, 0x31, 0x51, 0x62, 0xca, 0xc2, 0xf5, 0x48, 0x8f, 0x64,
	0x62, 0x3b, 0x33, 0x99, 0x4e, 0x23, 0x5c, 0x93, 0x37, 0x69, 0xda, 0xd2, 0x22, 0xfe, 0xa4, 0x2e,
	0xdf, 0x9e, 0xa7, 0xe7, 0xbc, 0x79, 0x92, 0x01, 0xe0, 0x22, 0x40, 0x57, 0x2a, 0xa1, 0x05, 0x31,
	0x58, 0x44, 0xa5, 0x43, 0xc1, 0xf2, 0x04, 0xd7, 0xb8, 0xd1, 0x64, 0x00, 0xed, 0x55, 0xc8, 0x90,
	0xeb, 0xbb, 0x99, 0x5d, 0x3f, 0xae, 0x9f, 0x77, 0xfc, 0x32, 0xa7, 0xb3, 0x24, 0x46, 0xb5, 0xa0,
	0x11, 0xda, 0x8d, 0x7c, 0x56, 0x64, 0x72, 0x04, 0xa0, 0x30, 0x96, 0x4f, 0x42, 0xbd, 0xa2, 0xb2,
	0x9b, 0xd9, 0xf4, 0xd3, 0x17, 0x67, 0x04, 0x3d, 0x4f, 0xf0, 0x17, 0xa6, 0x22, 0xaa, 0x99, 0xe0,
	0xe4, 0x3f, 0xb4, 0x62, 0x4d, 0x75, 0x12, 0x67, 0x57, 0xfa, 0xfe, 0x2e, 0x39, 0x37, 0x69, 0x95,
	0x28, 0xa2, 0x3c, 0x20, 0x04, 0x8c, 0xb4, 0xd2, 0xae, 0x86, 0xf1, 0xad, 0x5e, 0xe3, 0xb0, 0x9e,
	0x33, 0x06, 0xd3, 0x47, 0x19, 0x6e, 0x7f, 0xfc, 0x71, 0x7f, 0xaf, 0x71, 0x70, 0xef, 0x04, 0xcc,
	0xc9, 0x1b, 0x65, 0xd9, 0x66, 0x9e, 0x44, 0xd3, 0xad, 0xc6, 0xa2, 0x52, 0x99, 0x9d, 0x21, 0xb4,
	0x1f, 0x28, 0x0b, 0x6f, 0x59, 0x88, 0xc4, 0x06, 0x6b, 0x95, 0xba, 0xe2, 0xf9, 0xfe, 0x9e, 0x5f,
	0xc4, 0xeb, 0xf7, 0x26, 0x18, 0x0b, 0x11, 0x20, 0x71, 0xc1, 0x7a, 0x54, 0x28, 0xa9, 0x42, 0xd2,
	0x77, 0x53, 0xc1, 0xee, 0xce, 0xee, 0x80, 0x94, 0xb1, 0x34, 0xe1, 0xd4, 0xc8, 0x15, 0x98, 0x5e,
	0x28, 0xe2, 0x3f, 0xd2, 0x23, 0x68, 0x2d, 0x31, 0xc4, 0x95, 0xde, 0xe3, 0x99, 0xaf, 0x41, 0x37,
	0x8f, 0x99, 0x83, 0x9c, 0xf3, 0x14, 0x52, 0x8d, 0xd5, 0xdc, 0x0c, 0x43, 0xac, 0xe4, 0x86, 0x60,
	0xdc, 0xb3, 0xb8, 0xea, 0xea, 0x25, 0x74, 0x27, 0x52, 0x22, 0x0f, 0xa6, 0xb8, 0x66, 0xfc, 0x17,
	0x38, 0x33, 0xee, 0xd4, 0xc8, 0x05, 0x74, 0x72, 0x78, 0xce, 0x03, 0xf2, 0x2f, 0x9f, 0x15, 0xa2,
	0xbf, 0x2e, 0x3e, 0x03, 0x6b, 0xbe, 0x91, 0x09, 0x5f, 0x57, 0xf5, 0x3c, 0x05, 0x73, 0xa9, 0x85,
	0xaa, 0xc0, 0x9e, 0x5b, 0xd9, 0x03, 0x18, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x40, 0xe8,
	0x30, 0x0e, 0x03, 0x00, 0x00,
}
